services:
  django:
    container_name: django_test
    entrypoint: python manage.py runserver 0.0.0.0:8000
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8000:80
    expose:
      - 8000
    volumes:
    - .:/app
    depends_on:
    - db
    networks:
      nginx_network_test:
        aliases:
          - django_service
      database_network_test:

  nginx:
    container_name: nginx_test
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - nginx_network_test
    depends_on:
      - django
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M

  db:
    container_name: database_test
    image: postgres
    volumes:
      - ./postgres-test/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - database_network_test

networks:
  database_network_test:
    driver: bridge
  nginx_network_test:
    driver: bridge